### ISSUE TITLE
How does one pass a date type as an input?

### ISSUE THREAD

**Issue by vincentgiraud** [camunda/dmn-scala#18]
Hello,

I've succesfully tested passing strings or numbers as an input to decision tables but I can't figure out how date types.

No error is thrown when using "date" or "date and time" input types though result returns null.

Any change you could give a working example ?

Here is the outcome in the online [Camunda simulator](https://consulting.camunda.com/dmn-simulator/): 
<img width="1177" alt="Screenshot 2020-12-15 at 20 31 06" src="https://user-images.githubusercontent.com/11131880/102263415-906eac00-3f14-11eb-8056-f9a669c1c7b8.png">

**Comment by saig0** [comment]
Hi @vincentgiraud,

thank you for raising this up. Please share all required information to reproduce the issue:
* the DMN file
* the given input variables/context

**Comment by vincentgiraud** [comment]
Hello @saig0,  

Thanks for your reply. 
Here are the dmn and bpmn files tested with Zeebe 0.25.1:
[attestation.dmn.zip](https://github.com/camunda/dmn-scala/files/5720802/attestation.dmn.zip)
[test-dmn.bpmn.zip](https://github.com/camunda/dmn-scala/files/5720805/test-dmn.bpmn.zip)

The input variable `certificateDate` is already set to `= date and time("2020-06-15T00:00:00")` on the start-event event and should return `true`. Currently returns `null` in Zeebe Operate.
If set to "2020-06-14T00:00:00" it should return `false`.
If set to "2020-10-15T00:00:00" it should trigger a "no rule found" exception.

**Comment by saig0** [comment]
Thanks. I can reproduce the issue with the given files :+1: 

The problem here is not the DMN engine itself, it is more the integration in Zeebe :sweat_smile: In Zeebe, it is currently not possible to store a date-time variable directly. See here: https://docs.zeebe.io/reference/expressions.html#temporal-expressions

Instead, you need to transform the date-time into a string value: `= string(date and time("2020-06-15T00:00:00"))`

Since the date-time is a string, you need to transform it back to a date-time in the decision table. So, changing the input expression would do the trick: `date and time(certificateDate)`

Does this solve your issue?

**Comment by vincentgiraud** [comment]
Thank you, that was it 👍
